/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface CreateEvaluationRuleWithEvaluatorsRequest {
  /** Human-readable deployment name. */
  name: string;
  /**
   * One or more evaluator assignments. Providing the deprecated top-level `evaluator` or `mapping` fields alongside this is rejected with `400`.
   *
   * Multiple assignments are supported on writable targets.
   */
  evaluators: LangfuseAPI.unstable.CreateEvaluationRuleEvaluatorAssignment[];
  target: LangfuseAPI.unstable.EvaluationRuleTarget;
  enabled: boolean;
  sampling?: number;
  filter?: LangfuseAPI.unstable.EvaluationRuleFilter[];
}
