/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Evaluator family reference used when updating an evaluation rule.
 *
 * `name` identifies the evaluator family in the authenticated project context.
 * A rule's evaluator type cannot be changed, so this reference does not accept a `type`; the family must match the rule's current evaluator type.
 */
export interface EvaluationRuleEvaluatorReference {
  /** Evaluator family name. */
  name: string;
}
