/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface EvaluationRule
  extends LangfuseAPI.unstable.EvaluationRuleBase {
  /** Evaluators attached to this rule in deterministic assignment order. A `null` mapping inherits the evaluator version's default mapping. */
  evaluators: LangfuseAPI.unstable.EvaluationRuleEvaluatorAssignment[];
  /** Target object type that should trigger scoring. */
  target: LangfuseAPI.unstable.EvaluationRuleTarget;
  /** List of filter conditions used to decide whether a target should be evaluated. */
  filter: LangfuseAPI.unstable.EvaluationRuleFilter[];
  /** Deprecated compatibility alias containing the effective mapping for `evaluators[0]`. */
  mapping: LangfuseAPI.unstable.PromptVariableMappingRead[];
}
