/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * **Deprecated:** Connects one prompt variable to data from a trace, dataset item, or named observation in a legacy rule.
 */
export interface LegacyPromptVariableMapping {
  variable: string;
  langfuseObject: LangfuseAPI.unstable.LegacyEvaluationObject;
  /** Observation name to match, or `null` when `langfuseObject` is `trace` or `dataset_item`. */
  objectName: string | null;
  source: string;
  jsonPath?: string;
}
