/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * Maps one evaluator variable to a trace, dataset item, or field on a named observation in a legacy rule.
 */
export interface LegacyEvaluationRuleMapping {
  variable: string;
  langfuseObject: LangfuseAPI.unstable.LegacyEvaluationObject;
  /** Observation name to match, or `null` when `langfuseObject` is `trace` or `dataset_item`. */
  objectName: string | null;
  source: string;
  jsonPath?: string;
}
