/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface LegacyEvaluationRuleEvaluatorAssignment {
  evaluator: LangfuseAPI.unstable.EvaluationRuleEvaluator;
  mapping: LangfuseAPI.unstable.LegacyEvaluationRuleMapping[] | null;
}
