/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * Evaluation rule returned by list and get, including read-only legacy trace and dataset rules.
 */
export type ReadableEvaluationRule =
  | LangfuseAPI.unstable.EvaluationRule
  | LangfuseAPI.unstable.LegacyEvaluationRule;
