/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SkillVersionFileInput {
  path: string;
  /** UTF-8 text content. The server computes the hash and byte length. */
  content: string;
}
