/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SkillMeta {
  name: string;
  description: string;
  tags: string[];
  latestVersion: number;
  latestVersionCreatedAt: string;
  latestVersionLastUpdatedAt: string;
  /** Version assigned the production label, or null when no version is assigned. */
  productionVersion: number | null;
}
