/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SkillFile {
  id: string;
  path: string;
  blobId: string;
  sha256Hash: string;
  contentType: string;
  contentLength: number;
}
