/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SkillVersionFileReference {
  path: string;
  /** Canonical base64-encoded SHA-256 from a skill file manifest. The content must already exist in this project. */
  sha256Hash: string;
}
