/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateSkillRequest {
  /** The complete set of tags to apply to every version of the skill. Pass an empty list to clear all tags. */
  tags: string[];
}
