/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core/index.js";
import * as LangfuseAPI from "../../../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../../../core/headers.js";
import * as errors from "../../../../../../errors/index.js";

export declare namespace EvaluationRules {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-Langfuse-Sdk-Name header */
    xLangfuseSdkName?: core.Supplier<string | undefined>;
    /** Override the X-Langfuse-Sdk-Version header */
    xLangfuseSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-Langfuse-Public-Key header */
    xLangfusePublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-Langfuse-Sdk-Name header */
    xLangfuseSdkName?: string | undefined;
    /** Override the X-Langfuse-Sdk-Version header */
    xLangfuseSdkVersion?: string | undefined;
    /** Override the X-Langfuse-Public-Key header */
    xLangfusePublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class EvaluationRules {
  protected readonly _options: EvaluationRules.Options;

  constructor(_options: EvaluationRules.Options) {
    this._options = _options;
  }

  /**
   * Create an evaluation rule.
   *
   * An evaluation rule defines **what** incoming data should be evaluated and **how prompt variables should be populated** from that data.
   *
   * Use this resource after choosing an evaluator from the evaluator endpoints.
   *
   * Key rules:
   * - `name` must be unique within the project for public evaluation rules
   * - `target` must be `observation` or `experiment`
   * - `evaluator.name` + `evaluator.scope` must identify an existing evaluator family returned by the evaluator endpoints
   * - Langfuse resolves that family to its latest version before saving the evaluation rule
   * - for `target=experiment`, use dataset `id` values from `GET /api/public/v2/datasets` when filtering by `datasetId`
   * - for `llm_as_judge` evaluators, every evaluator prompt variable must be mapped exactly once
   * - for `code` evaluators, Langfuse uses the fixed code runtime mapping; omit `mapping` in create and update requests
   * - for user-provided `llm_as_judge` mappings, `expected_output` and `experiment_item_metadata` are only valid for `target=experiment`
   * - if `enabled=true`, Langfuse validates that the referenced evaluator can currently run
   * - at most 50 evaluation rules can be effectively active in one project at the same time
   *
   * If an evaluation rule with the same `name` already exists in the project, the API returns `409`.
   * In that case, update the existing resource with `PATCH /api/public/unstable/evaluation-rules/{evaluationRuleId}` instead of creating a second one.
   *
   * If enabling this resource would exceed the 50-active limit, the API also returns `409`.
   * In that case, disable or pause another active evaluation rule before enabling a new one.
   *
   * Current scope:
   * - evaluation rules are live-ingestion rules only
   * - they do not trigger historical backfills
   *
   * Recovery guidance:
   * - `400 invalid_filter_value`: fix the filter `column` or `value` using `details.column`, `details.invalidValues`, and `details.allowedValues`
   * - `400 invalid_filter_value` with `details.column=datasetId`: call `GET /api/public/v2/datasets`, then retry with dataset `id` values from that response
   * - `400 missing_variable_mapping`: for `llm_as_judge` evaluators, fetch the evaluator again and make sure every variable in `variables` appears exactly once in `mapping`
   * - `400 duplicate_variable_mapping`: remove repeated mappings for the same variable
   * - `400 invalid_variable_mapping`: for `llm_as_judge`, switch to a valid `source` for the selected `target`, or fix the variable name
   * - `400 invalid_json_path`: remove or correct the `jsonPath`
   * - `422 evaluator_preflight_failed`: the selected evaluator cannot run with the resolved model configuration. Fix the evaluator/default model setup, then retry the create request.
   *
   * @param {LangfuseAPI.unstable.CreateEvaluationRuleRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link LangfuseAPI.unstable.BadRequestError}
   * @throws {@link LangfuseAPI.unstable.UnauthorizedError}
   * @throws {@link LangfuseAPI.unstable.AccessDeniedError}
   * @throws {@link LangfuseAPI.unstable.NotFoundError}
   * @throws {@link LangfuseAPI.unstable.ConflictError}
   * @throws {@link LangfuseAPI.unstable.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.unstable.UnprocessableContentError}
   * @throws {@link LangfuseAPI.unstable.TooManyRequestsError}
   * @throws {@link LangfuseAPI.unstable.InternalServerError}
   * @throws {@link LangfuseAPI.Error}
   * @throws {@link LangfuseAPI.UnauthorizedError}
   * @throws {@link LangfuseAPI.AccessDeniedError}
   * @throws {@link LangfuseAPI.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.evaluationRules.create({
   *         name: "answer-correctness-live",
   *         evaluator: {
   *             name: "answer-correctness",
   *             scope: "project",
   *             type: "llm_as_judge"
   *         },
   *         target: "observation",
   *         enabled: true,
   *         sampling: 1,
   *         filter: [{
   *                 type: "stringOptions",
   *                 column: "type",
   *                 operator: "any of",
   *                 value: ["GENERATION"]
   *             }],
   *         mapping: [{
   *                 variable: "input",
   *                 source: "input"
   *             }, {
   *                 variable: "output",
   *                 source: "output"
   *             }]
   *     })
   *
   * @example
   *     await client.unstable.evaluationRules.create({
   *         name: "toxicity-code-live",
   *         evaluator: {
   *             name: "toxicity-detector",
   *             scope: "project",
   *             type: "code"
   *         },
   *         target: "observation",
   *         enabled: true,
   *         sampling: 1,
   *         filter: [{
   *                 type: "stringOptions",
   *                 column: "type",
   *                 operator: "any of",
   *                 value: ["GENERATION"]
   *             }]
   *     })
   *
   * @example
   *     await client.unstable.evaluationRules.create({
   *         name: "experiment-expected-output-match",
   *         evaluator: {
   *             name: "expected-output-match",
   *             scope: "project",
   *             type: "llm_as_judge"
   *         },
   *         target: "experiment",
   *         enabled: true,
   *         sampling: 0.5,
   *         filter: [{
   *                 type: "stringOptions",
   *                 column: "datasetId",
   *                 operator: "any of",
   *                 value: ["550e8400-e29b-41d4-a716-446655440000"]
   *             }],
   *         mapping: [{
   *                 variable: "output",
   *                 source: "output"
   *             }, {
   *                 variable: "expected_output",
   *                 source: "expected_output"
   *             }]
   *     })
   */
  public create(
    request: LangfuseAPI.unstable.CreateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<LangfuseAPI.unstable.EvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: LangfuseAPI.unstable.CreateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<LangfuseAPI.unstable.EvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-Langfuse-Sdk-Name":
          requestOptions?.xLangfuseSdkName ?? this._options?.xLangfuseSdkName,
        "X-Langfuse-Sdk-Version":
          requestOptions?.xLangfuseSdkVersion ??
          this._options?.xLangfuseSdkVersion,
        "X-Langfuse-Public-Key":
          requestOptions?.xLangfusePublicKey ??
          this._options?.xLangfusePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/evaluation-rules",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as LangfuseAPI.unstable.EvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new LangfuseAPI.unstable.BadRequestError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.unstable.UnauthorizedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.unstable.AccessDeniedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.unstable.NotFoundError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 409:
          throw new LangfuseAPI.unstable.ConflictError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.unstable.MethodNotAllowedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 422:
          throw new LangfuseAPI.unstable.UnprocessableContentError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new LangfuseAPI.unstable.TooManyRequestsError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new LangfuseAPI.unstable.InternalServerError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new LangfuseAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.LangfuseAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.LangfuseAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.LangfuseAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/unstable/evaluation-rules.",
        );
      case "unknown":
        throw new errors.LangfuseAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * List evaluation rules in the authenticated project.
   *
   * This includes legacy `trace` and `dataset` rules so they can be inspected and migrated to v4 rules. Legacy rules are read-only through this API; create, update, and delete continue to support only `observation` and `experiment` rules.
   *
   * @param {LangfuseAPI.unstable.ListEvaluationRulesRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link LangfuseAPI.unstable.BadRequestError}
   * @throws {@link LangfuseAPI.unstable.UnauthorizedError}
   * @throws {@link LangfuseAPI.unstable.AccessDeniedError}
   * @throws {@link LangfuseAPI.unstable.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.unstable.TooManyRequestsError}
   * @throws {@link LangfuseAPI.unstable.InternalServerError}
   * @throws {@link LangfuseAPI.Error}
   * @throws {@link LangfuseAPI.UnauthorizedError}
   * @throws {@link LangfuseAPI.AccessDeniedError}
   * @throws {@link LangfuseAPI.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.evaluationRules.list()
   */
  public list(
    request: LangfuseAPI.unstable.ListEvaluationRulesRequest = {},
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<LangfuseAPI.unstable.EvaluationRules> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: LangfuseAPI.unstable.ListEvaluationRulesRequest = {},
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<LangfuseAPI.unstable.EvaluationRules>> {
    const { page, limit } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (page != null) {
      _queryParams["page"] = page.toString();
    }

    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-Langfuse-Sdk-Name":
          requestOptions?.xLangfuseSdkName ?? this._options?.xLangfuseSdkName,
        "X-Langfuse-Sdk-Version":
          requestOptions?.xLangfuseSdkVersion ??
          this._options?.xLangfuseSdkVersion,
        "X-Langfuse-Public-Key":
          requestOptions?.xLangfusePublicKey ??
          this._options?.xLangfusePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/unstable/evaluation-rules",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as LangfuseAPI.unstable.EvaluationRules,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new LangfuseAPI.unstable.BadRequestError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.unstable.UnauthorizedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.unstable.AccessDeniedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.unstable.MethodNotAllowedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new LangfuseAPI.unstable.TooManyRequestsError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new LangfuseAPI.unstable.InternalServerError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new LangfuseAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.LangfuseAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.LangfuseAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.LangfuseAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/evaluation-rules.",
        );
      case "unknown":
        throw new errors.LangfuseAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get one evaluation rule by its identifier.
   *
   * Use this endpoint to inspect the current evaluator, target, mapping, filters, execution timing, and effective runtime status. Legacy `trace` and `dataset` rules are returned for migration and are read-only through this API.
   *
   * @param {string} evaluationRuleId - Evaluation rule identifier returned by the evaluation rule endpoints.
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link LangfuseAPI.unstable.BadRequestError}
   * @throws {@link LangfuseAPI.unstable.UnauthorizedError}
   * @throws {@link LangfuseAPI.unstable.AccessDeniedError}
   * @throws {@link LangfuseAPI.unstable.NotFoundError}
   * @throws {@link LangfuseAPI.unstable.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.unstable.TooManyRequestsError}
   * @throws {@link LangfuseAPI.unstable.InternalServerError}
   * @throws {@link LangfuseAPI.Error}
   * @throws {@link LangfuseAPI.UnauthorizedError}
   * @throws {@link LangfuseAPI.AccessDeniedError}
   * @throws {@link LangfuseAPI.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.evaluationRules.get("evaluationRuleId")
   */
  public get(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<LangfuseAPI.unstable.ReadableEvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(evaluationRuleId, requestOptions),
    );
  }

  private async __get(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<
    core.WithRawResponse<LangfuseAPI.unstable.ReadableEvaluationRule>
  > {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-Langfuse-Sdk-Name":
          requestOptions?.xLangfuseSdkName ?? this._options?.xLangfuseSdkName,
        "X-Langfuse-Sdk-Version":
          requestOptions?.xLangfuseSdkVersion ??
          this._options?.xLangfuseSdkVersion,
        "X-Langfuse-Public-Key":
          requestOptions?.xLangfusePublicKey ??
          this._options?.xLangfusePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as LangfuseAPI.unstable.ReadableEvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new LangfuseAPI.unstable.BadRequestError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.unstable.UnauthorizedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.unstable.AccessDeniedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.unstable.NotFoundError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.unstable.MethodNotAllowedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new LangfuseAPI.unstable.TooManyRequestsError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new LangfuseAPI.unstable.InternalServerError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new LangfuseAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.LangfuseAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.LangfuseAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.LangfuseAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/unstable/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.LangfuseAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update an evaluation rule.
   *
   * Typical uses:
   * - enable or disable live execution
   * - switch to another evaluator
   * - adjust sampling
   * - change filters
   * - update LLM-as-judge variable mappings
   *
   * Important behavior:
   * - provide only the fields you want to change
   * - if you provide `evaluator`, Langfuse resolves that evaluator family to its latest version before saving
   * - changing `target`, `filter`, or an LLM-as-judge `mapping` must still produce a valid target-specific configuration
   * - if you change `target` for an LLM-as-judge rule, also send a compatible `filter` and `mapping` in the same request unless the existing ones are still valid for the new target
   * - for `code` evaluator rules, omit `mapping`; Langfuse stores the fixed code runtime mapping automatically
   * - if the resulting config is enabled, Langfuse re-validates that the selected evaluator can run
   * - if the update would move a non-active evaluation rule into the active state and the project already has 50 active evaluation rules, the API returns `409`
   *
   * Recovery guidance:
   * - if an LLM-as-judge update fails with `missing_variable_mapping` or `invalid_variable_mapping` after changing `evaluator` or `target`, resend the request with a complete new `mapping`
   * - if the update fails with `invalid_filter_value` after changing `target`, resend the request with a target-compatible `filter`
   *
   * @param {string} evaluationRuleId - Evaluation rule identifier.
   * @param {LangfuseAPI.unstable.UpdateEvaluationRuleRequest} request
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link LangfuseAPI.unstable.BadRequestError}
   * @throws {@link LangfuseAPI.unstable.UnauthorizedError}
   * @throws {@link LangfuseAPI.unstable.AccessDeniedError}
   * @throws {@link LangfuseAPI.unstable.NotFoundError}
   * @throws {@link LangfuseAPI.unstable.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.unstable.UnprocessableContentError}
   * @throws {@link LangfuseAPI.unstable.TooManyRequestsError}
   * @throws {@link LangfuseAPI.unstable.InternalServerError}
   * @throws {@link LangfuseAPI.Error}
   * @throws {@link LangfuseAPI.UnauthorizedError}
   * @throws {@link LangfuseAPI.AccessDeniedError}
   * @throws {@link LangfuseAPI.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.evaluationRules.update("evaluationRuleId", {
   *         name: undefined,
   *         evaluator: undefined,
   *         target: undefined,
   *         enabled: undefined,
   *         sampling: undefined,
   *         filter: undefined,
   *         mapping: undefined
   *     })
   */
  public update(
    evaluationRuleId: string,
    request: LangfuseAPI.unstable.UpdateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<LangfuseAPI.unstable.EvaluationRule> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(evaluationRuleId, request, requestOptions),
    );
  }

  private async __update(
    evaluationRuleId: string,
    request: LangfuseAPI.unstable.UpdateEvaluationRuleRequest,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<core.WithRawResponse<LangfuseAPI.unstable.EvaluationRule>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-Langfuse-Sdk-Name":
          requestOptions?.xLangfuseSdkName ?? this._options?.xLangfuseSdkName,
        "X-Langfuse-Sdk-Version":
          requestOptions?.xLangfuseSdkVersion ??
          this._options?.xLangfuseSdkVersion,
        "X-Langfuse-Public-Key":
          requestOptions?.xLangfusePublicKey ??
          this._options?.xLangfusePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as LangfuseAPI.unstable.EvaluationRule,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new LangfuseAPI.unstable.BadRequestError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.unstable.UnauthorizedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.unstable.AccessDeniedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.unstable.NotFoundError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.unstable.MethodNotAllowedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 422:
          throw new LangfuseAPI.unstable.UnprocessableContentError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new LangfuseAPI.unstable.TooManyRequestsError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new LangfuseAPI.unstable.InternalServerError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new LangfuseAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.LangfuseAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.LangfuseAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.LangfuseAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/unstable/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.LangfuseAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete an evaluation rule.
   *
   * This removes the live-ingestion rule only. It does not delete the referenced evaluator.
   *
   * @param {string} evaluationRuleId - Evaluation rule identifier.
   * @param {EvaluationRules.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link LangfuseAPI.unstable.BadRequestError}
   * @throws {@link LangfuseAPI.unstable.UnauthorizedError}
   * @throws {@link LangfuseAPI.unstable.AccessDeniedError}
   * @throws {@link LangfuseAPI.unstable.NotFoundError}
   * @throws {@link LangfuseAPI.unstable.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.unstable.TooManyRequestsError}
   * @throws {@link LangfuseAPI.unstable.InternalServerError}
   * @throws {@link LangfuseAPI.Error}
   * @throws {@link LangfuseAPI.UnauthorizedError}
   * @throws {@link LangfuseAPI.AccessDeniedError}
   * @throws {@link LangfuseAPI.MethodNotAllowedError}
   * @throws {@link LangfuseAPI.NotFoundError}
   *
   * @example
   *     await client.unstable.evaluationRules.delete("evaluationRuleId")
   */
  public delete(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): core.HttpResponsePromise<LangfuseAPI.unstable.DeleteEvaluationRuleResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(evaluationRuleId, requestOptions),
    );
  }

  private async __delete(
    evaluationRuleId: string,
    requestOptions?: EvaluationRules.RequestOptions,
  ): Promise<
    core.WithRawResponse<LangfuseAPI.unstable.DeleteEvaluationRuleResponse>
  > {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-Langfuse-Sdk-Name":
          requestOptions?.xLangfuseSdkName ?? this._options?.xLangfuseSdkName,
        "X-Langfuse-Sdk-Version":
          requestOptions?.xLangfuseSdkVersion ??
          this._options?.xLangfuseSdkVersion,
        "X-Langfuse-Public-Key":
          requestOptions?.xLangfusePublicKey ??
          this._options?.xLangfusePublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/unstable/evaluation-rules/${encodeURIComponent(evaluationRuleId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as LangfuseAPI.unstable.DeleteEvaluationRuleResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new LangfuseAPI.unstable.BadRequestError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.unstable.UnauthorizedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.unstable.AccessDeniedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.unstable.NotFoundError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.unstable.MethodNotAllowedError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 429:
          throw new LangfuseAPI.unstable.TooManyRequestsError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 500:
          throw new LangfuseAPI.unstable.InternalServerError(
            _response.error.body as LangfuseAPI.unstable.PublicApiError,
            _response.rawResponse,
          );
        case 400:
          throw new LangfuseAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new LangfuseAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new LangfuseAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new LangfuseAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new LangfuseAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.LangfuseAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.LangfuseAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.LangfuseAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/unstable/evaluation-rules/{evaluationRuleId}.",
        );
      case "unknown":
        throw new errors.LangfuseAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
