/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface MembershipResponse {
  userId: string;
  role: LangfuseAPI.MembershipRole;
  email: string;
  name: string;
}
