/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * LLM API connection configuration (secrets excluded)
 */
export interface LlmConnection {
  id: string;
  /** Provider name (e.g., 'openai', 'my-gateway'). Must be unique in project, used for upserting. */
  provider: string;
  /** The adapter used to interface with the LLM */
  adapter: string;
  /** Masked version of the secret key for display purposes */
  displaySecretKey: string;
  /** Custom base URL for the LLM API */
  baseURL?: string;
  /** List of custom model names available for this connection */
  customModels: string[];
  /** Whether to include default models for this adapter */
  withDefaultModels: boolean;
  /** Keys of extra headers sent with requests (values excluded for security) */
  extraHeaderKeys: string[];
  createdAt: string;
  updatedAt: string;
}
