/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EvaluationRuleOptionsFilterOperator = "any of" | "none of";
export const EvaluationRuleOptionsFilterOperator = {
  AnyOf: "any of",
  NoneOf: "none of",
} as const;
