/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Structured score type returned by an evaluator.
 *
 * This controls the type of score value Langfuse stores for evaluation results:
 * - `NUMERIC`: a numeric score such as `0.82`
 * - `BOOLEAN`: a boolean score such as `true`
 * - `CATEGORICAL`: one or more category labels from a fixed list
 */
export type EvaluatorOutputScoreType = "NUMERIC" | "BOOLEAN" | "CATEGORICAL";
export const EvaluatorOutputScoreType = {
  Numeric: "NUMERIC",
  Boolean: "BOOLEAN",
  Categorical: "CATEGORICAL",
} as const;
