/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Connects one prompt variable to source data.
 *
 * `source` is `null` when the mapping is incomplete.
 *
 * @example
 *     {
 *         variable: "input",
 *         source: "input"
 *     }
 *
 * @example
 *     {
 *         variable: "input",
 *         source: null
 *     }
 */
export interface PromptVariableMappingRead {
  /** Prompt variable name without braces. */
  variable: string;
  /** Stored source field populating the variable, or `null` when the mapping is incomplete. */
  source: string | null;
  /** Optional JSONPath selector applied to the selected source. */
  jsonPath?: string;
}
