/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * Flat evaluator output definition returned by the public API.
 *
 * This response always includes `dataType` and never includes an internal output-definition `version`.
 * Optional empty descriptions from legacy definitions are omitted.
 *
 * @example
 *     {
 *         dataType: "NUMERIC",
 *         dataType: "NUMERIC",
 *         minValue: 0,
 *         maxValue: 1
 *     }
 *
 * @example
 *     {
 *         dataType: "CATEGORICAL",
 *         dataType: "CATEGORICAL",
 *         scoreReasoningInstructions: "Explain which label best fits the output.",
 *         scoreValueInstructions: "Choose the best label.",
 *         categories: ["correct", "partially_correct", "incorrect"],
 *         shouldAllowMultipleMatches: false
 *     }
 */
export type PublicEvaluatorOutputDefinition =
  | LangfuseAPI.PublicEvaluatorOutputDefinition.Numeric
  | LangfuseAPI.PublicEvaluatorOutputDefinition.Boolean
  | LangfuseAPI.PublicEvaluatorOutputDefinition.Categorical;

export namespace PublicEvaluatorOutputDefinition {
  export interface Numeric extends LangfuseAPI.PublicEvaluatorNumericScore {
    dataType: "NUMERIC";
  }

  export interface Boolean extends LangfuseAPI.PublicEvaluatorBooleanScore {
    dataType: "BOOLEAN";
  }

  export interface Categorical
    extends LangfuseAPI.PublicEvaluatorCategoricalScore {
    dataType: "CATEGORICAL";
  }
}
