/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface StringObjectEvaluationRuleFilter {
  /** Object-valued column to filter on. Currently only `metadata` is supported. */
  column: string;
  /** Top-level key inside the object-valued column to filter on. */
  key: string;
  operator: LangfuseAPI.EvaluationRuleStringFilterOperator;
  value: string;
}
