/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface CategoryOptionsEvaluationRuleFilter {
  /** Object-valued column to filter on. */
  column: string;
  /** Key inside the object-valued column to filter on. */
  key: string;
  operator: LangfuseAPI.unstable.EvaluationRuleOptionsFilterOperator;
  value: string[];
}
