/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Effective runtime status of the evaluation rule.
 *
 * - `active`: enabled and currently runnable.
 * - `inactive`: disabled by configuration.
 * - `paused`: enabled, but Langfuse has blocked execution until the underlying issue is resolved.
 */
export type EvaluationRuleStatus = "active" | "inactive" | "paused";
export const EvaluationRuleStatus = {
  Active: "active",
  Inactive: "inactive",
  Paused: "paused",
} as const;
