/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * One filter condition used to decide whether a live-ingested target should be evaluated.
 *
 * An evaluation rule can include zero or more filter objects. All filters must be satisfied for the target to run.
 *
 * How to build a valid filter object:
 * - Pick the `target` first, because it changes the supported columns.
 * - Pick the filter `type`. That determines which fields are required.
 * - Use `key` only for object filters such as `metadata`.
 * - Use the correct `value` shape for the chosen filter `type`.
 *
 * Operator quick reference by filter `type`:
 * - `string`: `"="`, `contains`, `does not contain`, `starts with`, `ends with`
 * - `number`: `"="`, `">"`, `"<"`, `">="`, `"<="`
 * - `datetime`: `"="`, `">"`, `"<"`, `">="`, `"<="`
 * - `stringOptions`: `any of`, `none of`
 * - `arrayOptions`: `any of`, `none of`, `all of`
 * - `stringObject`: same operators as `string`
 * - `null`: `is null`, `is not null`
 *
 * Supported columns by target:
 * - `target=observation`
 *   - `type`: `stringOptions`, operators `any of` / `none of`, values `GENERATION`, `SPAN`, `EVENT`
 *   - `name`: `stringOptions`, operators `any of` / `none of`
 *   - `environment`: `stringOptions`, operators `any of` / `none of`
 *   - `level`: `stringOptions`, operators `any of` / `none of`, values `DEBUG`, `DEFAULT`, `WARNING`, `ERROR`
 *   - `version`: `string`
 *   - `traceName`: `stringOptions`, operators `any of` / `none of`
 *   - `userId`: `string`
 *   - `sessionId`: `string`
 *   - `tags`: `arrayOptions`, operators `any of` / `none of` / `all of`
 *   - `metadata`: `stringObject` with `key`
 *   - `parentObservationId`: `null`, operators `is null` / `is not null`
 *   - `calledToolNames`: `arrayOptions`, operators `any of` / `none of` / `all of`
 *   - `toolCalls`: `number`
 * - `target=experiment`
 *   - `datasetId`: `stringOptions`, operators `any of` / `none of`
 *     Use dataset `id` values from `GET /api/public/v2/datasets`, not dataset names.
 *
 * Recovery guidance:
 * - `invalid_filter_value` with `details.column` but no `invalidValues`: the selected `column` is not supported for the chosen `target`
 * - `invalid_filter_value` with `details.invalidValues`: the selected values are not allowed for that column. Replace them with one of `details.allowedValues` when provided.
 * - `invalid_filter_value` for `column=datasetId`: call `GET /api/public/v2/datasets`, then retry with dataset `id` values from that response.
 *
 * @example
 *     {
 *         type: "stringOptions",
 *         column: "type",
 *         operator: LangfuseAPI.unstable.EvaluationRuleOptionsFilterOperator.AnyOf,
 *         value: ["GENERATION"]
 *     }
 *
 * @example
 *     {
 *         type: "stringObject",
 *         column: "metadata",
 *         key: "customerTier",
 *         operator: LangfuseAPI.unstable.EvaluationRuleStringFilterOperator.Equals,
 *         value: "enterprise"
 *     }
 *
 * @example
 *     {
 *         type: "null",
 *         column: "parentObservationId",
 *         operator: LangfuseAPI.unstable.EvaluationRuleNullFilterOperator.IsNull
 *     }
 *
 * @example
 *     {
 *         type: "arrayOptions",
 *         column: "tags",
 *         operator: LangfuseAPI.unstable.EvaluationRuleArrayOptionsFilterOperator.AnyOf,
 *         value: ["production"]
 *     }
 *
 * @example
 *     {
 *         type: "stringOptions",
 *         column: "datasetId",
 *         operator: LangfuseAPI.unstable.EvaluationRuleOptionsFilterOperator.AnyOf,
 *         value: ["550e8400-e29b-41d4-a716-446655440000"]
 *     }
 */
export type EvaluationRuleFilter =
  | LangfuseAPI.unstable.EvaluationRuleFilter.Datetime
  | LangfuseAPI.unstable.EvaluationRuleFilter.String
  | LangfuseAPI.unstable.EvaluationRuleFilter.Number
  | LangfuseAPI.unstable.EvaluationRuleFilter.StringOptions
  | LangfuseAPI.unstable.EvaluationRuleFilter.CategoryOptions
  | LangfuseAPI.unstable.EvaluationRuleFilter.ArrayOptions
  | LangfuseAPI.unstable.EvaluationRuleFilter.StringObject
  | LangfuseAPI.unstable.EvaluationRuleFilter.NumberObject
  | LangfuseAPI.unstable.EvaluationRuleFilter.Boolean
  | LangfuseAPI.unstable.EvaluationRuleFilter.Null;

export namespace EvaluationRuleFilter {
  export interface Datetime
    extends LangfuseAPI.unstable.DateTimeEvaluationRuleFilter {
    type: "datetime";
  }

  export interface String
    extends LangfuseAPI.unstable.StringEvaluationRuleFilter {
    type: "string";
  }

  export interface Number
    extends LangfuseAPI.unstable.NumberEvaluationRuleFilter {
    type: "number";
  }

  export interface StringOptions
    extends LangfuseAPI.unstable.StringOptionsEvaluationRuleFilter {
    type: "stringOptions";
  }

  export interface CategoryOptions
    extends LangfuseAPI.unstable.CategoryOptionsEvaluationRuleFilter {
    type: "categoryOptions";
  }

  export interface ArrayOptions
    extends LangfuseAPI.unstable.ArrayOptionsEvaluationRuleFilter {
    type: "arrayOptions";
  }

  export interface StringObject
    extends LangfuseAPI.unstable.StringObjectEvaluationRuleFilter {
    type: "stringObject";
  }

  export interface NumberObject
    extends LangfuseAPI.unstable.NumberObjectEvaluationRuleFilter {
    type: "numberObject";
  }

  export interface Boolean
    extends LangfuseAPI.unstable.BooleanEvaluationRuleFilter {
    type: "boolean";
  }

  export interface Null extends LangfuseAPI.unstable.NullEvaluationRuleFilter {
    type: "null";
  }
}
