/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Where an evaluator comes from.
 *
 * - `project`: created in your project
 * - `managed`: provided by Langfuse
 */
export type EvaluatorScope = "project" | "managed";
export const EvaluatorScope = {
  Project: "project",
  Managed: "managed",
} as const;
