/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The evaluator engine type.
 *
 * The unstable public API currently supports only LLM-as-a-judge evaluators.
 */
export type EvaluatorType = "llm_as_judge";
export const EvaluatorType = {
  LlmAsJudge: "llm_as_judge",
} as const;
