/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface PublicCategoricalEvaluatorOutputDefinition {
  /** Always `CATEGORICAL`. */
  dataType: LangfuseAPI.unstable.EvaluatorOutputDataType;
  reasoning: LangfuseAPI.unstable.EvaluatorOutputFieldDefinition;
  score: LangfuseAPI.unstable.PublicCategoricalEvaluatorOutputScoreDefinition;
}
