/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface StringEvaluationRuleFilter {
  /** Column to filter on. */
  column: string;
  operator: LangfuseAPI.unstable.EvaluationRuleStringFilterOperator;
  value: string;
}
