/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface StringObjectEvaluationRuleFilter {
  /** Object-valued column to filter on. In the unstable public API this is currently `metadata`. */
  column: string;
  /** Top-level key inside the object-valued column to filter on. */
  key: string;
  operator: LangfuseAPI.unstable.EvaluationRuleStringFilterOperator;
  value: string;
}
