/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface SubmitFeedbackRequest {
  /** Category of the thing the feedback is about. */
  targetType: LangfuseAPI.FeedbackTargetType;
  /** The specific instance within targetType: the skill name, MCP tool name, CLI command, API endpoint path, or docs page path (e.g. 'queryMetrics', '/docs/mcp'). An identifier, not a sentence. Must be between 1 and 200 characters. */
  target: string;
  /** Concise feedback text approved by the user. Must be between 1 and 3000 characters. */
  feedback: string;
  /** Optional user-approved goal or use case they were trying to achieve. Must be between 1 and 1500 characters when provided. Do not include secrets, customer data, trace payloads, or broad unrelated context. */
  goal?: string;
  /** Optional HTTP(S) reference URL. Langfuse stores it as text for triage and does not fetch it. */
  referenceUrl?: string;
}
