/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface PaginatedAnnotationQueueItems {
  data: LangfuseAPI.AnnotationQueueItem[];
  meta: LangfuseAPI.utils.MetaResponse;
}
