/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../index.js";

/**
 * @example
 *     {
 *         resourceSpans: [{
 *                 resource: {
 *                     attributes: [{
 *                             key: "service.name",
 *                             value: {
 *                                 stringValue: "my-service"
 *                             }
 *                         }, {
 *                             key: "service.version",
 *                             value: {
 *                                 stringValue: "1.0.0"
 *                             }
 *                         }]
 *                 },
 *                 scopeSpans: [{
 *                         scope: {
 *                             name: "langfuse-sdk",
 *                             version: "2.60.3"
 *                         },
 *                         spans: [{
 *                                 traceId: "0123456789abcdef0123456789abcdef",
 *                                 spanId: "0123456789abcdef",
 *                                 name: "my-operation",
 *                                 kind: 1,
 *                                 startTimeUnixNano: "1747872000000000000",
 *                                 endTimeUnixNano: "1747872001000000000",
 *                                 attributes: [{
 *                                         key: "langfuse.observation.type",
 *                                         value: {
 *                                             stringValue: "generation"
 *                                         }
 *                                     }],
 *                                 status: {}
 *                             }]
 *                     }]
 *             }]
 *     }
 */
export interface OtelTraceRequest {
  /** Array of resource spans containing trace data as defined in the OTLP specification */
  resourceSpans: LangfuseAPI.OtelResourceSpan[];
}
