/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as LangfuseAPI from "../../../index.js";
import * as core from "../../../../core/index.js";

export class EvaluationNotFoundError extends errors.LangfuseAPIError {
  constructor(
    body: LangfuseAPI.PublicApiError,
    rawResponse?: core.RawResponse,
  ) {
    super({
      message: "EvaluationNotFoundError",
      statusCode: 404,
      body: body,
      rawResponse: rawResponse,
    });
    Object.setPrototypeOf(this, EvaluationNotFoundError.prototype);
  }
}
