/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMediaResponse {
  /** The unique langfuse identifier of a media record */
  mediaId: string;
  /** The MIME type of the media record */
  contentType: string;
  /** The size of the media record in bytes */
  contentLength: number;
  /** The date and time when the media record was uploaded */
  uploadedAt: string;
  /** The download URL of the media record */
  url: string;
  /** The expiry date and time of the media record download URL */
  urlExpiry: string;
}
