/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationScheme {
  name: string;
  description: string;
  specUri: string;
  type: string;
  primary: boolean;
}
