/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface ScimUser {
  schemas: string[];
  id: string;
  userName: string;
  name: LangfuseAPI.ScimName;
  emails: LangfuseAPI.ScimEmail[];
  meta: LangfuseAPI.UserMeta;
}
