/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BlobStorageExportFrequency =
  | "every_20_minutes"
  | "hourly"
  | "daily"
  | "weekly";
export const BlobStorageExportFrequency = {
  Every20Minutes: "every_20_minutes",
  Hourly: "hourly",
  Daily: "daily",
  Weekly: "weekly",
} as const;
