/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * File type reported for an existing integration. Includes `PARQUET`, which a project may enable through the Langfuse UI but cannot yet be set via this API (the request `fileType` omits it).
 */
export type BlobStorageIntegrationFileTypeResponse =
  | "JSON"
  | "CSV"
  | "JSONL"
  | "PARQUET";
export const BlobStorageIntegrationFileTypeResponse = {
  Json: "JSON",
  Csv: "CSV",
  Jsonl: "JSONL",
  Parquet: "PARQUET",
} as const;
