/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * What data the integration exports.
 * - `LEGACY_TRACES_OBSERVATIONS`: traces, observations, and scores tables. Observation columns are controlled by `exportFieldGroups`; field groups without a counterpart in this data model (e.g. `trace_context`) are omitted.
 * - `OBSERVATIONS_V2`: same data model as the `/api/public/v2/observations` endpoint, plus scores. Columns are controlled by `exportFieldGroups`.
 * - `LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS`: both sets. Observation columns of both portions are controlled by `exportFieldGroups`.
 *
 * **Note:** which sources a deployment accepts depends on how far it has moved to the v4 data model. `OBSERVATIONS_V2` and the enriched-observations portion of `LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS` read the enriched observations table, so they require a deployment that already populates it. `LEGACY_TRACES_OBSERVATIONS` and the legacy portion of `LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS` read the legacy traces and observations tables, so they require a deployment that still populates those. A deployment part-way through the migration populates both and accepts every source. Selecting a source the deployment cannot serve is rejected with `400`, rather than exporting an empty result. See https://langfuse.com/docs/v4.
 */
export type BlobStorageExportSource =
  | "LEGACY_TRACES_OBSERVATIONS"
  | "OBSERVATIONS_V2"
  | "LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS";
export const BlobStorageExportSource = {
  LegacyTracesObservations: "LEGACY_TRACES_OBSERVATIONS",
  ObservationsV2: "OBSERVATIONS_V2",
  LegacyTracesAndEnrichedObservations:
    "LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS",
} as const;
