/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * Individual span representing a unit of work or operation
 */
export interface OtelSpan {
  /** Trace ID (16 bytes, hex-encoded string in JSON or Buffer in binary) */
  traceId?: unknown;
  /** Span ID (8 bytes, hex-encoded string in JSON or Buffer in binary) */
  spanId?: unknown;
  /** Parent span ID if this is a child span */
  parentSpanId?: unknown;
  /** Span name describing the operation */
  name?: string;
  /** Span kind (1=INTERNAL, 2=SERVER, 3=CLIENT, 4=PRODUCER, 5=CONSUMER) */
  kind?: number;
  /** Start time in nanoseconds since Unix epoch */
  startTimeUnixNano?: unknown;
  /** End time in nanoseconds since Unix epoch */
  endTimeUnixNano?: unknown;
  /** Span attributes including Langfuse-specific attributes (langfuse.observation.*) */
  attributes?: LangfuseAPI.OtelAttribute[];
  /** Span status object */
  status?: unknown;
}
