/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * @example
 *     [{
 *             name: "accuracy",
 *             value: 0.9,
 *             traceId: "cdef-1234-5678-90ab"
 *         }, {
 *             name: "helpfulness",
 *             value: 1,
 *             dataType: LangfuseAPI.ScoreDataType.Boolean,
 *             traceId: "cdef-1234-5678-90ab"
 *         }]
 */
export type CreateScoreBatchRequest = LangfuseAPI.CreateScoreRequest[];
