/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export type CreateScoresResponse =
  | LangfuseAPI.CreateScoreBatchResults
  | LangfuseAPI.CreateScoreResponse
  | LangfuseAPI.CreateScoreBatchResponse;
