/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export type CreateScoresRequest =
  | LangfuseAPI.CreateScoreRequest
  | LangfuseAPI.CreateScoreBatchRequest;
