/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * A reference to the entity this score is attached to. Discriminated by "kind" — one of trace, observation, session, or experiment.
 */
export type ScoreSubject =
  /**
   * Subject is a trace-level score. */
  | LangfuseAPI.ScoreSubject.Trace
  /**
   * Subject is an observation-level score scoped to a trace. */
  | LangfuseAPI.ScoreSubject.Observation
  /**
   * Subject is a session-level score. */
  | LangfuseAPI.ScoreSubject.Session
  /**
   * Subject is a dataset run (experiment) score. */
  | LangfuseAPI.ScoreSubject.Experiment;

export namespace ScoreSubject {
  export interface Trace extends LangfuseAPI.ScoreSubjectTrace {
    kind: "trace";
  }

  export interface Observation extends LangfuseAPI.ScoreSubjectObservation {
    kind: "observation";
  }

  export interface Session extends LangfuseAPI.ScoreSubjectSession {
    kind: "session";
  }

  export interface Experiment extends LangfuseAPI.ScoreSubjectExperiment {
    kind: "experiment";
  }
}
