/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         metadata: undefined,
 *         retention: undefined
 *     }
 */
export interface UpdateProjectRequest {
  name: string;
  /** Optional metadata for the project */
  metadata?: Record<string, unknown>;
  /**
   * Number of days to retain data.
   * Must be 0 or at least 3 days.
   * Requires data-retention entitlement for non-zero values.
   * Optional. Will retain existing retention setting if omitted.
   */
  retention?: number;
}
