/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreatePresetPlacement {
  /** Server-generated when omitted. */
  id?: string;
  presetId: string;
  /** Grid column (12-column grid). Defaults to `0`. */
  x?: number;
  /** Grid row. Defaults to the first row below all existing tiles. */
  y?: number;
  /** Width in grid columns. Defaults to `6`. */
  width?: number;
  /** Height in grid rows. Defaults to `6`. */
  height?: number;
}
