/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface Dashboard {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string;
  definition: LangfuseAPI.unstable.DashboardDefinition;
  /** Dashboard-level filters applied to all widgets on the dashboard. */
  filters: LangfuseAPI.unstable.DashboardWidgetFilter[];
}
