/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface DashboardList {
  data: LangfuseAPI.unstable.Dashboard[];
  meta: LangfuseAPI.utils.MetaResponse;
}
