/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PresetPlacement {
  id: string;
  presetId: string;
  x: number;
  y: number;
  width: number;
  height: number;
}
