/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WidgetPlacement {
  id: string;
  widgetId: string;
  x: number;
  y: number;
  width: number;
  height: number;
}
