/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Source values accepted when creating a score via the public REST API.
 * EVAL is reserved for internal evaluator outputs and is intentionally not
 * exposed here — use commons.ScoreSource when reading scores.
 */
export type CreateScoreSource = "API" | "ANNOTATION";
export const CreateScoreSource = {
  Api: "API",
  Annotation: "ANNOTATION",
} as const;
