/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface CreateModelRequest {
  /** Name of the model definition. If multiple with the same name exist, they are applied in the following order: (1) custom over built-in, (2) newest according to startTime where model.startTime<observation.startTime */
  modelName: string;
  /** Regex pattern which matches this model definition to generation.model. Useful in case of fine-tuned models. If you want to exact match, use `(?i)^modelname$` */
  matchPattern: string;
  /** Apply only to generations which are newer than this ISO date. */
  startDate?: string;
  /** Unit used by this model. */
  unit?: LangfuseAPI.ModelUsageUnit;
  /** Price (USD) per input unit */
  inputPrice?: number;
  /** Price (USD) per output unit */
  outputPrice?: number;
  /** Price (USD) per total units. Cannot be set if input or output price is set. */
  totalPrice?: number;
  /** Optional. Tokenizer to be applied to observations which match to this model. See docs for more details. */
  tokenizerId?: string;
  /** Optional. Configuration for the selected tokenizer. Needs to be JSON. See docs for more details. */
  tokenizerConfig?: unknown;
}
