/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Tokenizer supported by Langfuse for model usage inference.
 */
export type ModelTokenizerId = "openai" | "claude";
export const ModelTokenizerId = {
  Openai: "openai",
  Claude: "claude",
} as const;
