/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export type GetScoresResponseData =
  | LangfuseAPI.legacy.GetScoresResponseData.Numeric
  | LangfuseAPI.legacy.GetScoresResponseData.Categorical
  | LangfuseAPI.legacy.GetScoresResponseData.Boolean
  | LangfuseAPI.legacy.GetScoresResponseData.Correction
  | LangfuseAPI.legacy.GetScoresResponseData.Text;

export namespace GetScoresResponseData {
  export interface Numeric
    extends LangfuseAPI.legacy.GetScoresResponseDataNumeric {
    dataType: "NUMERIC";
  }

  export interface Categorical
    extends LangfuseAPI.legacy.GetScoresResponseDataCategorical {
    dataType: "CATEGORICAL";
  }

  export interface Boolean
    extends LangfuseAPI.legacy.GetScoresResponseDataBoolean {
    dataType: "BOOLEAN";
  }

  export interface Correction
    extends LangfuseAPI.legacy.GetScoresResponseDataCorrection {
    dataType: "CORRECTION";
  }

  export interface Text extends LangfuseAPI.legacy.GetScoresResponseDataText {
    dataType: "TEXT";
  }
}
