/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The value of the score. Must be passed as string for categorical scores, and numeric for boolean and numeric scores
 */
export type CreateScoreValue = number | string;
