/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DatasetItemMediaReferenceField =
  | "input"
  | "expected_output"
  | "metadata";
export const DatasetItemMediaReferenceField = {
  Input: "input",
  ExpectedOutput: "expected_output",
  Metadata: "metadata",
} as const;
