/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface NumericScore extends LangfuseAPI.BaseScore {
  /** The numeric value of the score */
  value: number;
}
