/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * An observation from the v2 API with field-group-based selection.
 * Core fields are always present. Other fields are included only when their field group is requested.
 */
export interface ObservationV2 {
  /** The unique identifier of the observation */
  id: string;
  /** The trace ID associated with the observation */
  traceId: string | null;
  /** The start time of the observation */
  startTime: string;
  /** The end time of the observation */
  endTime: string | null;
  /** The project ID this observation belongs to */
  projectId: string;
  /** The parent observation ID */
  parentObservationId: string | null;
  /** The type of the observation (e.g. GENERATION, SPAN, EVENT) */
  type: string;
  /** The name of the observation */
  name?: string | null;
  /** The level of the observation */
  level?: LangfuseAPI.ObservationLevel;
  /** The status message of the observation */
  statusMessage?: string | null;
  /** The version of the observation */
  version?: string | null;
  /** The environment from which this observation originated */
  environment?: string | null;
  /** Whether the observation is bookmarked */
  bookmarked?: boolean;
  /** Whether the observation is public */
  public?: boolean;
  /** The user ID associated with the observation */
  userId?: string | null;
  /** The session ID associated with the observation */
  sessionId?: string | null;
  /** The completion start time of the observation */
  completionStartTime?: string | null;
  /** The creation timestamp of the observation */
  createdAt?: string;
  /** The last update timestamp of the observation */
  updatedAt?: string;
  /** The input data of the observation */
  input?: unknown;
  /** The output data of the observation */
  output?: unknown;
  /** Additional metadata of the observation */
  metadata?: unknown;
  /** The model name as provided by the user */
  providedModelName?: string | null;
  /** The internal model ID matched by Langfuse */
  internalModelId?: string | null;
  /** The parameters of the model used for the observation */
  modelParameters?: unknown;
  /** The usage details of the observation. Key is the usage metric name, value is the number of units consumed. */
  usageDetails?: Record<string, number>;
  /** The cost details of the observation. Key is the cost metric name, value is the cost in USD. */
  costDetails?: Record<string, number>;
  /** The total cost of the observation in USD */
  totalCost?: number | null;
  /** The prompt ID associated with the observation */
  promptId?: string | null;
  /** The prompt name associated with the observation */
  promptName?: string | null;
  /** The prompt version associated with the observation */
  promptVersion?: number | null;
  /** The latency in seconds */
  latency?: number | null;
  /** The time to first token in seconds */
  timeToFirstToken?: number | null;
  /** The matched model ID */
  modelId?: string | null;
}
