/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * Condition for matching a pricing tier against usage details or observation attributes.
 *
 * Usage-detail conditions treat usageDetailPattern as a regex, sum all matching usage values, and compare the sum to the numeric value. Model-parameter and metadata conditions match an exact top-level key against one or more string values.
 */
export type PricingTierCondition =
  | LangfuseAPI.PricingTierUsageCondition
  | LangfuseAPI.PricingTierAttributeCondition;
