/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ScoreDataType = "NUMERIC" | "BOOLEAN" | "CATEGORICAL";
export const ScoreDataType = {
  Numeric: "NUMERIC",
  Boolean: "BOOLEAN",
  Categorical: "CATEGORICAL",
} as const;
