/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Session {
  id: string;
  createdAt: string;
  projectId: string;
  /** The environment from which this session originated. */
  environment?: string;
}
