/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Trace {
  /** The unique identifier of a trace */
  id: string;
  /** The timestamp when the trace was created */
  timestamp: string;
  /** The name of the trace */
  name?: string;
  /** The input data of the trace. Can be any JSON. */
  input?: unknown;
  /** The output data of the trace. Can be any JSON. */
  output?: unknown;
  /** The session identifier associated with the trace */
  sessionId?: string;
  /** The release version of the application when the trace was created */
  release?: string;
  /** The version of the trace */
  version?: string;
  /** The user identifier associated with the trace */
  userId?: string;
  /** The metadata associated with the trace. Can be any JSON. */
  metadata?: unknown;
  /** The tags associated with the trace. Can be an array of strings or null. */
  tags?: string[];
  /** Public traces are accessible via url without login */
  public?: boolean;
  /** The environment from which this trace originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'. */
  environment?: string;
}
