/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * (Deprecated. Use usageDetails and costDetails instead.) Standard interface for usage and cost
 */
export interface Usage {
  /** Number of input units (e.g. tokens) */
  input: number;
  /** Number of output units (e.g. tokens) */
  output: number;
  /** Defaults to input+output if not set */
  total: number;
  /** Unit of measurement */
  unit: string | null;
  /** USD input cost */
  inputCost?: number;
  /** USD output cost */
  outputCost?: number;
  /** USD total cost, defaults to input+output */
  totalCost?: number;
}
