/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response for API key creation
 */
export interface ApiKeyResponse {
  id: string;
  createdAt: string;
  publicKey: string;
  secretKey: string;
  displaySecretKey: string;
  note?: string;
}
