/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Summary of an API key
 */
export interface ApiKeySummary {
  id: string;
  createdAt: string;
  expiresAt?: string;
  lastUsedAt?: string;
  note?: string;
  publicKey: string;
  displaySecretKey: string;
}
