/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BasePrompt {
  name: string;
  version: number;
  config?: unknown;
  /** List of deployment labels of this prompt version. */
  labels: string[];
  /** List of tags. Used to filter via UI and API. The same across versions of a prompt. */
  tags: string[];
  /** Commit message for this prompt version. */
  commitMessage?: string;
  /** The dependency resolution graph for the current prompt. Null if the prompt has no dependencies or if `resolve=false` was used. */
  resolutionGraph?: Record<string, unknown>;
}
