/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * Request body for creating an evaluator.
 *
 * If the same `name` already exists in your project, Langfuse creates the next version and returns it.
 * Existing evaluation rules in the same project are then moved to that new latest version automatically.
 * If `type` is omitted, Langfuse defaults it to `llm_as_judge` for backwards compatibility.
 */
export type CreateEvaluatorRequest =
  | LangfuseAPI.unstable.CreateEvaluatorRequest.LlmAsJudge
  | LangfuseAPI.unstable.CreateEvaluatorRequest.Code;

export namespace CreateEvaluatorRequest {
  export interface LlmAsJudge
    extends LangfuseAPI.unstable.CreateLlmAsJudgeEvaluatorRequest {
    type: "llm_as_judge";
  }

  export interface Code
    extends LangfuseAPI.unstable.CreateCodeEvaluatorRequest {
    type: "code";
  }
}
