/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

/**
 * Request body for creating an evaluator.
 *
 * If the same `name` already exists in your project, Langfuse creates the next version and returns it.
 * Existing evaluation rules in the same project are then moved to that new latest version automatically.
 */
export interface CreateEvaluatorRequest {
  /** Evaluator name within the authenticated project. */
  name: string;
  /** Prompt template used by the evaluator. */
  prompt: string;
  /**
   * Structured output schema the evaluator must return.
   *
   * Always send `dataType`.
   * Do not send `version`; it is an internal storage detail and not part of the public request contract.
   */
  outputDefinition: LangfuseAPI.unstable.EvaluatorOutputDefinition;
  /** Optional explicit model configuration. Omit or set to `null` to use the project default evaluation model. */
  modelConfig?: LangfuseAPI.unstable.EvaluatorModelConfig | null;
}
