/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface EvaluatorBase {
  /** Identifier of this evaluator. */
  id: string;
  /** Evaluator name. */
  name: string;
  /** Version number of this evaluator. */
  version: number;
  /** Where this evaluator comes from: your project or Langfuse-managed defaults. */
  scope: LangfuseAPI.unstable.EvaluatorScope;
  /**
   * Variables that can be mapped when creating an evaluation rule.
   *
   * LLM evaluators require every variable to be mapped exactly once. Code evaluators always expose the fixed runtime payload fields and Langfuse maps them automatically.
   */
  variables: string[];
  /** Number of evaluation rules in the project that currently use this evaluator version. */
  evaluationRuleCount: number;
  /** Timestamp when this evaluator was created. */
  createdAt: string;
  /** Timestamp when this evaluator was last updated. */
  updatedAt: string;
}
