/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface CodeEvaluatorVersion extends LangfuseAPI.EvaluatorVersionBase {
  /** Evaluator type. */
  type: "code";
  /** Source code executed for each matched observation. */
  sourceCode: string;
  /** Runtime language used to execute the source code. */
  sourceCodeLanguage: LangfuseAPI.CodeEvaluatorSourceCodeLanguage;
}
