/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CursorMeta {
  /** Opaque cursor for the next page. Omitted when there is no next page. */
  cursor?: string;
}
