/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * An ordered list of chat messages. A system message is only allowed as the first message.
 */
export type EvaluatorChatPrompt = LangfuseAPI.EvaluatorChatMessage[];
