/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * One chat message in an evaluator prompt.
 */
export interface EvaluatorChatMessage {
  role: LangfuseAPI.EvaluatorChatMessageRole;
  /** Message content. Evaluator variables use `{{variable}}` syntax. */
  content: string;
}
