/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

/**
 * A list containing exactly one user chat message.
 */
export type EvaluatorChatPrompt = LangfuseAPI.EvaluatorChatMessage[];
