/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface EvaluatorVersionBase {
  /** Stable identifier of this evaluator version. */
  id: string;
  /** Monotonically increasing evaluator version number. */
  version: number;
  /** Timestamp when this evaluator version was created. */
  createdAt: string;
  /** User who created this version, or `null` when no user can be resolved. */
  createdBy: LangfuseAPI.Creator | null;
}
