/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Explicit model configuration for an evaluator.
 *
 * If the complete `modelConfig` is `null`, Langfuse uses the project's default evaluation model.
 * If provided, the model must be available to the project when the evaluator or evaluation rule is enabled.
 *
 * @example
 *     {
 *         provider: "openai",
 *         model: "gpt-4.1-mini"
 *     }
 */
export interface EvaluatorModelConfig {
  /**
   * Provider identifier, for example `openai` or `anthropic`.
   *
   * To discover valid values for the current project, call `GET /api/public/llm-connections` and use one of the returned `provider` values.
   */
  provider: string;
  /** Model identifier exposed by the provider, for example `gpt-4.1-mini`. */
  model: string;
}
