/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Metadata-only update. At least one field must be provided.
 */
export interface UpdateEvaluatorMetadataRequest {
  /** New human-readable evaluator name. */
  name?: string;
  /** New description. Set to `null` to clear it. */
  description?: string | null;
}
