/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface UpdateLlmAsJudgeEvaluatorRequest {
  /** New human-readable evaluator name. */
  name?: string;
  /** New description. Set to `null` to clear it. */
  description?: string | null;
  /** Evaluator type. The type of an existing evaluator cannot change. */
  type: "llm_as_judge";
  /** Complete replacement user prompt string or a list containing exactly one user chat message. */
  prompt: LangfuseAPI.EvaluatorChatPromptInput;
  /** Explicit model configuration. Set to `null` or omit to use the project's default evaluation model. */
  modelConfig?: LangfuseAPI.EvaluatorModelConfig | null;
  /** Complete replacement default variable mapping, or `null` when no default is configured. */
  variableMapping?: LangfuseAPI.PromptVariableMappingInput[] | null;
  /** Complete replacement output schema. Do not include an internal persistence version. */
  outputDefinition: LangfuseAPI.EvaluatorOutputDefinition;
}
