/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListDashboardWidgetsRequest {
  /** 1-based page number. Defaults to `1`. */
  page?: number;
  /** Maximum number of items per page. Defaults to `50`. */
  limit?: number;
}
