/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         newLabels: ["newLabels", "newLabels"]
 *     }
 */
export interface UpdatePromptRequest {
  /** New labels for the prompt version. Labels are unique across versions. The "latest" label is reserved and managed by Langfuse. */
  newLabels: string[];
}
