/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DashboardWidgetSortOrder = "ASC" | "DESC";
export const DashboardWidgetSortOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
