/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DashboardWidgetChartType =
  | "LINE_TIME_SERIES"
  | "AREA_TIME_SERIES"
  | "BAR_TIME_SERIES"
  | "HORIZONTAL_BAR"
  | "VERTICAL_BAR"
  | "PIE"
  | "NUMBER"
  | "HISTOGRAM"
  | "PIVOT_TABLE";
export const DashboardWidgetChartType = {
  LineTimeSeries: "LINE_TIME_SERIES",
  AreaTimeSeries: "AREA_TIME_SERIES",
  BarTimeSeries: "BAR_TIME_SERIES",
  HorizontalBar: "HORIZONTAL_BAR",
  VerticalBar: "VERTICAL_BAR",
  Pie: "PIE",
  Number: "NUMBER",
  Histogram: "HISTOGRAM",
  PivotTable: "PIVOT_TABLE",
} as const;
