/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DashboardWidgetMetricAggregation =
  | "sum"
  | "avg"
  | "count"
  | "max"
  | "min"
  | "p50"
  | "p75"
  | "p90"
  | "p95"
  | "p99"
  | "histogram"
  | "uniq";
export const DashboardWidgetMetricAggregation = {
  Sum: "sum",
  Avg: "avg",
  Count: "count",
  Max: "max",
  Min: "min",
  P50: "p50",
  P75: "p75",
  P90: "p90",
  P95: "p95",
  P99: "p99",
  Histogram: "histogram",
  Uniq: "uniq",
} as const;
