/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../../../index.js";

export interface DashboardWidgetList {
  data: LangfuseAPI.unstable.DashboardWidget[];
  meta: LangfuseAPI.utils.MetaResponse;
}
