/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface BaseScoreV3 {
  id: string;
  projectId: string;
  name: string;
  source: LangfuseAPI.ScoreSource;
  timestamp: string;
  /** The environment from which this score originated. */
  environment: string;
  createdAt: string;
  updatedAt: string;
  /** Optional comment attached to the score. Present when "details" is included in the fields parameter. */
  comment?: string | null;
  /** The score config ID, if this score was created from a config. Present when "details" is included in the fields parameter. */
  configId?: string | null;
  /** Arbitrary metadata attached to the score. Present when "details" is included in the fields parameter. */
  metadata?: Record<string, unknown>;
  /** The user who created this score, if available. Present when "annotation" is included in the fields parameter. */
  authorUserId?: string | null;
  /** The annotation queue this score belongs to, if any. Present when "annotation" is included in the fields parameter. */
  queueId?: string | null;
  /** The entity this score is attached to (trace, observation, session, or experiment). Present when "subject" is included in the fields parameter. */
  subject?: LangfuseAPI.ScoreSubjectV3;
}
