/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export type ScoreV3 =
  /**
   * Score with NUMERIC data type. Value is a number. */
  | LangfuseAPI.ScoreV3.Numeric
  /**
   * Score with BOOLEAN data type. Value is a boolean. */
  | LangfuseAPI.ScoreV3.Boolean
  /**
   * Score with CATEGORICAL data type. Value is a string category. */
  | LangfuseAPI.ScoreV3.Categorical
  /**
   * Score with TEXT data type. Value is a string. */
  | LangfuseAPI.ScoreV3.Text
  /**
   * Score with CORRECTION data type. Value is the correction string. */
  | LangfuseAPI.ScoreV3.Correction;

export namespace ScoreV3 {
  export interface Numeric extends LangfuseAPI.NumericScoreV3 {
    dataType: "NUMERIC";
  }

  export interface Boolean extends LangfuseAPI.BooleanScoreV3 {
    dataType: "BOOLEAN";
  }

  export interface Categorical extends LangfuseAPI.CategoricalScoreV3 {
    dataType: "CATEGORICAL";
  }

  export interface Text extends LangfuseAPI.TextScoreV3 {
    dataType: "TEXT";
  }

  export interface Correction extends LangfuseAPI.CorrectionScoreV3 {
    dataType: "CORRECTION";
  }
}
