/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScoreSubjectObservationV3 {
  /** The observation ID. */
  id: string;
  /** The parent trace ID, if available. */
  traceId?: string;
}
