/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One request validation issue.
 */
export interface PublicApiValidationIssue {
  /** Validator issue code. */
  code: string;
  /** Human-readable explanation. */
  message: string;
  /** Path to the invalid request field. */
  path: unknown[];
}
