/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface CreateGenerationBody extends LangfuseAPI.CreateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, LangfuseAPI.MapValue>;
  usage?: LangfuseAPI.IngestionUsage;
  usageDetails?: LangfuseAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptName?: string;
  promptVersion?: number;
}
