/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface IngestionResponse {
  successes: LangfuseAPI.IngestionSuccess[];
  errors: LangfuseAPI.IngestionError[];
}
