/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Usage interface of OpenAI for improved compatibility.
 */
export interface OpenAiUsage {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
}
