/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as LangfuseAPI from "../../../index.js";

export interface UpdateGenerationEvent extends LangfuseAPI.BaseEvent {
  body: LangfuseAPI.UpdateGenerationBody;
}
