/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCommentRequest {
  /** The id of the project to attach the comment to. */
  projectId: string;
  /** The type of the object to attach the comment to (trace, observation, session, prompt). */
  objectType: string;
  /** The id of the object to attach the comment to. If this does not reference a valid existing object, an error will be thrown. */
  objectId: string;
  /** The content of the comment. May include markdown. Currently limited to 5000 characters. */
  content: string;
  /** The id of the user who created the comment. */
  authorUserId?: string;
  /** For inline comments on IO, specifies which field (input, output, or metadata). Must be set together with path, rangeStart, and rangeEnd. */
  dataField?: string;
  /** JSON Path expressions specifying comment location within the dataField. Must have same length as rangeStart and rangeEnd. */
  path?: string[];
  /** Start character offsets (inclusive, UTF-16 code units) for each path entry. */
  rangeStart?: number[];
  /** End character offsets (exclusive, UTF-16 code units) for each path entry. */
  rangeEnd?: number[];
}
