/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Metadata for cursor-based pagination.
 */
export interface CursorMetaResponse {
  /** Opaque cursor for the next page. Omitted when there is no next page. */
  cursor?: string;
}
